flowman:
  version: @flowman.version@
  plugins:
    - flowman-avro
    - flowman-aws
    - flowman-mariadb
    - flowman-mysql


# List of subdirectories containing Flowman projects
projects:
  - flow


packages:
  distd:
    kind: dist

  jard:
    kind: fatjar
