# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - site

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttp.proxyHost=${http_proxy_host} -Dhttp.proxyPort=${http_proxy_port} -Dhttps.proxyHost=${http_proxy_host} -Dhttps.proxyPort=${http_proxy_port} -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:ReservedCodeCacheSize=512m"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # SpotBugs currently doesn't work, maybe because of the custom image
  SAST_EXCLUDED_ANALYZERS: "spotbugs"

image: dimajix/maven-npm:latest

# Cache downloaded dependencies and plugins between builds.
cache:
  key: flowman-maven-plugin-${CI_JOB_NAME}
  paths:
    - .m2/repository
    - .npm


# Default build variant
build-default:
  stage: build
  script: 'mvn ${MAVEN_CLI_OPTS} clean package'


# Run security tests
sast:
  stage: test


# Build site and reports
build-site:
  stage: site
  script: 'mvn ${MAVEN_CLI_OPTS} clean install -DskipTests -Ddockerfile.skip && mvn ${MAVEN_CLI_OPTS} site'
  artifacts:
    name: "flowman-site"
    paths:
      - target/site
    expire_in: 5 days


